# Generated by Django 2.0.9 on 2019-05-02 09:09

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
