# Generated by Django 2.0.9 on 2019-06-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190502_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Music', 'music'), ('Painting&Drawing', 'painting&drawing'), ('Photography', 'photography')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('owner', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(to='users.Content'),
        ),
    ]
