# Generated by Django 2.0.9 on 2019-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190615_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(to='users.Category'),
        ),
    ]
