# Generated by Django 2.2.2 on 2019-06-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190615_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
