# Generated by Django 2.2.2 on 2019-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('painting&drawing', 'Painting&Drawing'), ('photography', 'Photography')], default=None, max_length=20),
        ),
    ]
