# Generated by Django 2.2.2 on 2019-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190628_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default=None, max_length=20),
        ),
    ]
