# Generated by Django 2.2.2 on 2019-06-28 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 12, 52, 27, 73413)),
        ),
    ]
