# Generated by Django 2.2.2 on 2019-06-28 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_content_date_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('date_published',)},
        ),
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('painting&drawing', 'Painting&Drawing'), ('photography', 'Photography')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 12, 57, 21, 901966)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
