# Generated by Django 2.2.2 on 2019-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190628_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_published',
            field=models.DateTimeField(default=None),
        ),
    ]
