# Generated by Django 2.2.2 on 2019-07-02 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190628_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
